In [226]:
import numpy as np
import random
from collections import defaultdict
import networkx as nx
import time
import pdb

<h1>Part 1</h1>

In [227]:
"""
Dijkstra
"""

class Graph(): 
   
    def __init__(self, matrix): 
        self.V = matrix.shape[0] 
        self.graph = matrix
   
    def returnSolution(self, dist): 
        #print ("Vertex tDistance from Source") 
        sol={}
        for node in range(self.V): 
            #print (node, "t", dist[node]) 
            sol[node] = dist[node]
        return sol

    def minDistance(self, dist, sptSet): 
        min = float('inf') 
        min_index=0
        for v in range(self.V): 
            if dist[v] < min and sptSet[v] == False: 
                min = dist[v] 
                min_index = v 
        return min_index 
    
    def dijkstra(self, src): 
        dist = [float('inf')] * self.V 
        dist[src] = 0
        sptSet = [False] * self.V 
        for cout in range(self.V): 
            u = self.minDistance(dist, sptSet) 
            sptSet[u] = True
            for v in range(self.V): 
                if self.graph[u][v] > 0 and sptSet[v] == False and dist[v] > dist[u] + self.graph[u][v]: 
                    dist[v] = dist[u] + self.graph[u][v] 
        sol = self.returnSolution(dist)
        return sol

In [228]:
"""
The Bellman-Ford 
"""
def initialize(graph, source):
    d = {} 
    p = {} 
    for node in graph:
        d[node] = float('Inf') 
        p[node] = None
    d[source] = 0 
    return d, p

def relax(node, neighbour, graph, d, p): 
    if d[neighbour] > d[node] + graph[node][neighbour]:
        d[neighbour]  = d[node] + graph[node][neighbour]
        p[neighbour] = node

def bellman_ford(graph, source):
    d, p = initialize(graph, source)
    for i in range(len(graph)-1): 
        for u in graph:
            for v in graph[u]:
                relax(u, v, graph, d, p) 
    for u in graph:
        for v in graph[u]:
            assert d[v] <= d[u] + graph[u][v]

    return d, p



    

In [262]:
def random_adjacency_matrix(n,e):   
    A = np.zeros((n,n))
    for i in range(e):
        ed = edge = 0
        while ed == edge:
            ed = np.random.randint(0, high=n)
            edge = np.random.randint(0, high=n)
        weight = np.random.randint(0,high=10)
        A[ed,edge] = weight
        A[edge,ed] = weight
    return A

def random_grid_with_walls(n,e):   
    A = np.zeros((n,n))
    for i in range(e):
        ed = edge = 0
        while ed == edge:
            ed = np.random.randint(0, high=n)
            edge = np.random.randint(0, high=n)
        A[ed,edge] = 1
        A[edge,ed] = 1
    return A

def convert(A): 
    adjList = defaultdict(list) 
    for i in range(len(A)): 
        adjList[i] = []
        for j in range(len(A[i])): 
                       if A[i][j] > 0: 
                           adjList[i].append({j:A[i][j]}) 
    return adjList 

def convert_w(A): 
    adjList = {} 
    for i in range(len(A)): 
        adjList[i] = {}
        for j in range(len(A[i])): 
                       if A[i][j] > 0: 
                           adjList[i][j] = A[i][j]
    return adjList 

In [263]:
m = random_adjacency_matrix(100,500)

In [264]:
g = Graph(m)

In [265]:
g.graph

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [270]:
g.dijkstra(np.random.randint(0,high=100))

{0: 7.0,
 1: 8.0,
 2: 6.0,
 3: 4.0,
 4: 6.0,
 5: 4.0,
 6: 7.0,
 7: 8.0,
 8: 6.0,
 9: 5.0,
 10: 7.0,
 11: 8.0,
 12: 5.0,
 13: 9.0,
 14: 8.0,
 15: 9.0,
 16: 6.0,
 17: 9.0,
 18: 8.0,
 19: 6.0,
 20: 11.0,
 21: 6.0,
 22: 5.0,
 23: 8.0,
 24: 7.0,
 25: 8.0,
 26: 6.0,
 27: 4.0,
 28: 4.0,
 29: 8.0,
 30: 5.0,
 31: 5.0,
 32: 12.0,
 33: 6.0,
 34: 8.0,
 35: 10.0,
 36: 9.0,
 37: 4.0,
 38: 8.0,
 39: 8.0,
 40: 11.0,
 41: 0,
 42: 7.0,
 43: 8.0,
 44: 3.0,
 45: 1.0,
 46: 6.0,
 47: 7.0,
 48: 7.0,
 49: 10.0,
 50: 8.0,
 51: 10.0,
 52: 6.0,
 53: 3.0,
 54: 2.0,
 55: 8.0,
 56: 7.0,
 57: 3.0,
 58: 6.0,
 59: 7.0,
 60: 3.0,
 61: 8.0,
 62: 9.0,
 63: 4.0,
 64: 5.0,
 65: 4.0,
 66: 8.0,
 67: 5.0,
 68: 9.0,
 69: 7.0,
 70: 8.0,
 71: 4.0,
 72: 6.0,
 73: 8.0,
 74: 11.0,
 75: 5.0,
 76: 4.0,
 77: 8.0,
 78: 3.0,
 79: 7.0,
 80: 7.0,
 81: 8.0,
 82: 8.0,
 83: 6.0,
 84: 6.0,
 85: 7.0,
 86: 7.0,
 87: 8.0,
 88: 8.0,
 89: 7.0,
 90: 7.0,
 91: 7.0,
 92: 9.0,
 93: 2.0,
 94: 6.0,
 95: 5.0,
 96: 8.0,
 97: 9.0,
 98: 6.0,
 99: 9.0}

In [283]:
averages = []
start_v = np.random.randint(0,high=100)
for i in range(10):
    start = time.perf_counter() 
    g.dijkstra(start_v)         
    averages.append(time.perf_counter()  - start)
average = sum(averages)/10

In [284]:
#Here's the average running time of Dijkstra with 100 vertices and 500 edges
average

0.01352332760579884

In [285]:
g1 = convert_w(m)

In [328]:
g1

{0: {19: 3.0, 22: 2.0, 35: 3.0, 40: 7.0, 60: 8.0, 69: 6.0, 87: 7.0},
 1: {9: 5.0, 32: 5.0, 33: 6.0, 43: 4.0, 58: 3.0, 60: 5.0},
 2: {3: 3.0, 13: 4.0, 37: 4.0, 51: 4.0, 71: 2.0, 81: 2.0, 96: 8.0},
 3: {2: 3.0,
  16: 3.0,
  31: 5.0,
  53: 1.0,
  55: 4.0,
  58: 7.0,
  64: 1.0,
  78: 6.0,
  87: 4.0},
 4: {8: 7.0, 18: 3.0, 20: 6.0, 35: 9.0, 51: 5.0, 58: 3.0, 93: 4.0},
 5: {10: 7.0,
  21: 4.0,
  32: 8.0,
  52: 3.0,
  58: 2.0,
  78: 1.0,
  80: 6.0,
  86: 3.0,
  93: 3.0},
 6: {7: 5.0,
  16: 4.0,
  30: 6.0,
  37: 5.0,
  64: 2.0,
  67: 5.0,
  75: 5.0,
  77: 6.0,
  98: 5.0},
 7: {6: 5.0, 21: 2.0, 60: 6.0, 64: 8.0, 74: 5.0, 85: 7.0, 90: 2.0, 94: 9.0},
 8: {4: 7.0, 10: 3.0, 48: 9.0, 64: 1.0, 72: 5.0, 83: 4.0, 85: 7.0, 90: 6.0},
 9: {1: 5.0,
  11: 3.0,
  19: 7.0,
  29: 9.0,
  37: 1.0,
  38: 8.0,
  45: 5.0,
  47: 2.0,
  48: 2.0,
  84: 1.0,
  94: 3.0,
  99: 9.0},
 10: {5: 7.0,
  8: 3.0,
  16: 8.0,
  17: 6.0,
  22: 8.0,
  30: 4.0,
  52: 3.0,
  53: 9.0,
  55: 6.0,
  57: 4.0,
  71: 5.0,
  86: 2.0,
  94: 

In [286]:
distances, path = bellman_ford(g1,0)

In [192]:
distances

{0: 0,
 1: 5.0,
 2: 7.0,
 3: 10.0,
 4: 8.0,
 5: 5.0,
 6: 8.0,
 7: 7.0,
 8: 7.0,
 9: 3.0,
 10: 8.0,
 11: 16.0,
 12: 11.0,
 13: 8.0,
 14: 5.0,
 15: 8.0,
 16: 7.0,
 17: 10.0,
 18: 11.0,
 19: 7.0,
 20: 9.0,
 21: 3.0,
 22: 8.0,
 23: 5.0,
 24: 6.0,
 25: 7.0,
 26: 10.0,
 27: 2.0,
 28: 7.0,
 29: 9.0,
 30: 5.0,
 31: 9.0,
 32: 5.0,
 33: 8.0,
 34: 6.0,
 35: 8.0,
 36: 9.0,
 37: 8.0,
 38: 6.0,
 39: 10.0,
 40: 9.0,
 41: 4.0,
 42: 3.0,
 43: 2.0,
 44: 10.0,
 45: 4.0,
 46: 5.0,
 47: 8.0,
 48: 7.0,
 49: 5.0,
 50: 9.0,
 51: 1.0,
 52: 7.0,
 53: 10.0,
 54: 7.0,
 55: 8.0,
 56: 7.0,
 57: 4.0,
 58: 5.0,
 59: 9.0,
 60: 2.0,
 61: 7.0,
 62: 5.0,
 63: 5.0,
 64: 8.0,
 65: 5.0,
 66: 4.0,
 67: 7.0,
 68: 7.0,
 69: 9.0,
 70: 7.0,
 71: 7.0,
 72: 4.0,
 73: 6.0,
 74: 6.0,
 75: 11.0,
 76: 7.0,
 77: 6.0,
 78: 5.0,
 79: 5.0,
 80: 1.0,
 81: 7.0,
 82: 9.0,
 83: 6.0,
 84: 8.0,
 85: 5.0,
 86: 7.0,
 87: 5.0,
 88: 7.0,
 89: 5.0,
 90: 8.0,
 91: 4.0,
 92: 8.0,
 93: 8.0,
 94: 6.0,
 95: 6.0,
 96: 12.0,
 97: 6.0,
 98: 5.0,
 99: inf}

In [287]:
path

{0: None,
 1: 60,
 2: 3,
 3: 53,
 4: 18,
 5: 78,
 6: 64,
 7: 90,
 8: 64,
 9: 48,
 10: 86,
 11: 88,
 12: 27,
 13: 14,
 14: 46,
 15: 47,
 16: 46,
 17: 23,
 18: 66,
 19: 0,
 20: 96,
 21: 61,
 22: 0,
 23: 48,
 24: 42,
 25: 22,
 26: 78,
 27: 22,
 28: 54,
 29: 67,
 30: 63,
 31: 71,
 32: 5,
 33: 67,
 34: 86,
 35: 0,
 36: 18,
 37: 16,
 38: 18,
 39: 83,
 40: 0,
 41: 54,
 42: 35,
 43: 72,
 44: 54,
 45: 27,
 46: 22,
 47: 14,
 48: 19,
 49: 50,
 50: 48,
 51: 97,
 52: 69,
 53: 27,
 54: 53,
 55: 3,
 56: 26,
 57: 19,
 58: 5,
 59: 98,
 60: 22,
 61: 46,
 62: 86,
 63: 54,
 64: 27,
 65: 19,
 66: 19,
 67: 22,
 68: 67,
 69: 0,
 70: 42,
 71: 57,
 72: 46,
 73: 21,
 74: 88,
 75: 63,
 76: 27,
 77: 16,
 78: 22,
 79: 39,
 80: 44,
 81: 86,
 82: 47,
 83: 64,
 84: 9,
 85: 19,
 86: 64,
 87: 0,
 88: 46,
 89: 25,
 90: 12,
 91: 18,
 92: 89,
 93: 60,
 94: 65,
 95: 65,
 96: 35,
 97: 50,
 98: 42,
 99: 85}

In [288]:
averages_bf = []
for i in range(10):
    start = time.perf_counter() 
    bellman_ford(g1,start_v)         
    averages.append(time.perf_counter()  - start)
average_bf = sum(averages)/10

In [289]:
#Here's the average running time of Dijkstra with 100 vertices and 500 edges
average_bf

0.06541453700629063

<h1>Part 2</h1>

In [324]:
import heapq

class Node:
    def __init__(self, parent=None, position=None):
        self.parent = parent
        self.position = position

        self.g = 0
        self.h = 0
        self.f = 0

    def __eq__(self, other):
        return self.position == other.position
    
    def __repr__(self):
        return f"{self.position} - g: {self.g} h: {self.h} f: {self.f}"

    # defining less than for purposes of heap queue
    def __lt__(self, other):
        return self.f < other.f
    
    # defining greater than for purposes of heap queue
    def __gt__(self, other):
        return self.f > other.f

def return_path(current_node):
    path = []
    current = current_node
    while current is not None:
        path.append(current.position)
        current = current.parent
    return path[::-1]  # Return reversed path


def astar(maze, start, end, allow_diagonal_movement = False):
    
    # Create start and end node
    start_node = Node(None, start)
    start_node.g = start_node.h = start_node.f = 0
    end_node = Node(None, end)
    end_node.g = end_node.h = end_node.f = 0

    # Initialize both open and closed list
    open_list = []
    closed_list = []

    # Heapify the open_list and Add the start node
    heapq.heapify(open_list) 
    heapq.heappush(open_list, start_node)

    # Adding a stop condition
    outer_iterations = 0
    max_iterations = (len(maze[0]) * len(maze) // 2)

    # what squares do we search
    adjacent_squares = ((0, -1), (0, 1), (-1, 0), (1, 0),)
    if allow_diagonal_movement:
        adjacent_squares = ((0, -1), (0, 1), (-1, 0), (1, 0), (-1, -1), (-1, 1), (1, -1), (1, 1),)

    # Loop until you find the end
    while len(open_list) > 0:
        outer_iterations += 1

        if outer_iterations > max_iterations:
          # if we hit this point return the path such as it is
          # it will not contain the destination
            #print("Giving up on pathfinding too many iterations")
            return None
            #return return_path(current_node)       
        
        # Get the current node
        current_node = heapq.heappop(open_list)
        closed_list.append(current_node)

        # Found the goal
        if current_node == end_node:
            return return_path(current_node)

        # Generate children
        children = []
        
        for new_position in adjacent_squares: # Adjacent squares
            node_position = (current_node.position[0] + new_position[0], current_node.position[1] + new_position[1])
            if node_position[0] > (len(maze) - 1) or node_position[0] < 0 or node_position[1] > (len(maze[len(maze)-1]) -1) or node_position[1] < 0:
                continue
            if maze[node_position[0]][node_position[1]] != 0:
                continue

            new_node = Node(current_node, node_position)

            children.append(new_node)

        for child in children:
            if len([closed_child for closed_child in closed_list if closed_child == child]) > 0:
                continue

            child.g = current_node.g + 1
            child.h = ((child.position[0] - end_node.position[0]) ** 2) + ((child.position[1] - end_node.position[1]) ** 2)
            child.f = child.g + child.h

            if len([open_node for open_node in open_list if child.position == open_node.position and child.g > open_node.g]) > 0:
                continue

            heapq.heappush(open_list, child)

    print("Couldn't get a path to destination")
    return None

def a_star_printer(maze, print_maze = True):

    if print_maze:
        for step in path:
            maze[step[0]][step[1]] = 2
            
        for row in maze:
            line = []
            for col in row:
                if col == 1:
                    line.append("\u2588")
                elif col == 0:
                    line.append(" ")
                elif col == 2:
                    line.append(".")
            print("".join(line))
    print(path)

In [327]:
maze = random_grid_with_walls(10,30)
print(maze)
counter = 1
for i in range(10):
    
    path = None
    while path is None: 
        tic = time.perf_counter() 
        start_cell = (np.random.randint(0,high=10),np.random.randint(0,high=10))
        finish_cell = (np.random.randint(0,high=10),np.random.randint(0,high=10))
        while start_cell == finish_cell:
            finish_cell = (np.random.randint(0,high=10),np.random.randint(0,high=10))
        path = astar(maze, start_cell, finish_cell, allow_diagonal_movement=True)
        counter +=1
        toc = time.perf_counter()
        time_taken = toc-tic
    
    print("This is run number {}".format(i))
    print("Start: {}, End: {}".format(start_cell, finish_cell))
    print("Running time: ", time_taken)    
    a_star_printer(maze.copy())
    print("+++++++++++++++++++++++++++++++")
    
print("It took {} times to pick two random cells to get 10 full paths in the grid".format(counter))
        

[[0. 1. 0. 1. 0. 1. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 1. 1. 1.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 1. 0. 0. 1. 1. 0.]
 [0. 1. 0. 1. 0. 0. 1. 0. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 1. 1. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 1.]
 [0. 1. 0. 1. 1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 0. 1. 0. 0. 1. 1. 0.]]
This is run number 0
Start: (7, 2), End: (7, 6)
Running time:  0.0004787130164913833
 █ █ █   █
█ █ █ ████
 █ █     █
█ █ █  ██ 
 █ █  █ ██
█     █   
 █ .██    
 █.█...  █
 █ ██    █
███ █  ██ 
[(7, 2), (6, 3), (7, 4), (7, 5), (7, 6)]
+++++++++++++++++++++++++++++++
This is run number 1
Start: (7, 4), End: (1, 3)
Running time:  0.0006164519872982055
 █ █ █   █
█ █.█ ████
 █.█     █
█ █.█  ██ 
 █.█  █ ██
█  .  █   
 █ .██    
 █ █.    █
 █ ██    █
███ █  ██ 
[(7, 4), (6, 3), (5, 3), (4, 2), (3, 3), (2, 2), (1, 3)]
+++++++++++++++++++++++++++++++
This is run number 2
Start: (7, 8), End: (1, 3)
Running time:  0.0007602580008096993
 █ █ █   █
█ █.█ ████
 █ █..   █